#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

USER_REPO="leenooks/phpLDAPadmin"
VERSION=$(gh_releases ${USER_REPO} | sort -V | tail -1)
URL="https://github.com/${USER_REPO}/archive/${VERSION}.tar.gz"

SRC=/usr/local/src
dl $URL $SRC
mv $SRC/$VERSION.tar.gz $SRC/phpldapadmin.tar.gz
