#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="master.tar.gz"
URL="https://github.com/leenooks/phpLDAPadmin/archive/$VERSION"

dl $URL /usr/local/src
