#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="1.2.3/phpldapadmin-1.2.3.tgz"
URL="http://sourceforge.net/projects/phpldapadmin/files/phpldapadmin-php5/$VERSION"

dl $URL /usr/local/src

