#!/bin/sh -ex

LDAP_PASS=turnkey
LDAP_DOMAIN=example.com

SRC=/usr/local/src

# phpldapadmin: create base configuration
cat >/etc/phpldapadmin/config.php<<EOF
<?php
// phpLDAPadmin configuration

\$config->custom->jpeg['tmpdir'] = '/tmp';
\$config->custom->session['blowfish'] = '$(mcookie)$(mcookie)';
\$config->custom->appearance['hide_template_warning'] = true;
// Uncomment the line below to only use the tkl custom templates
//\$config->custom->appearance['custom_templates_only'] = true;

\$servers = new Datastore();
\$servers->newServer('ldap_pla');
\$servers->setValue('server','name','TurnKey OpenLDAP');
\$servers->setValue('server','base',array('cn=config',''));
\$servers->setValue('server','hide_noaccess_base','true');
\$servers->setValue('login','bind_id','');
// Set to true to allow anonymous bind login.
\$servers->setValue('login','anon_bind',false);
\$servers->setValue('custom','pages_prefix','tkl-');
\$servers->setValue('auto_number','enable',true);
\$servers->setValue('auto_number','mechanism','search');
\$servers->setValue('auto_number','search_base','');
\$servers->setValue('auto_number','min',array('uidNumber'=>2000,'gidNumber'=>2000));
?>
EOF

# phpldapadmin: tweak footer
CONF=/usr/share/phpldapadmin/lib/page.php
sed -i "s|</body>.*|<div id=\"turnkey-credit\" style=\"text-align:center;font-size:11px;\"><a href=\"https://www.turnkeylinux.org/openldap\">OpenLDAP Appliance</a> - Powered by <a href=\"https://www.turnkeylinux.org\">TurnKey Linux</a></div></body>';|" $CONF

# phpldapadmin: enable in lighttpd
lighty-disable-mod ssl
lighty-enable-mod phpldapadmin

# copy the samba schema to the ldap config directory
mv /usr/share/doc/samba/examples/LDAP/samba.schema /etc/ldap/schema/
mv /usr/share/doc/samba/examples/LDAP/samba.ldif /etc/ldap/schema/

# TODO apt hook?
# ldapscripts: enable params to be configured in inithook
CONF=/etc/ldapscripts/ldapscripts.conf
sed -i "s|^#SERVER|SERVER|" $CONF
sed -i "s|^#BINDDN|BINDDN|" $CONF
sed -i "s|^#SUFFIX|SUFFIX|" $CONF
sed -i "s|^#GSUFFIX|GSUFFIX|" $CONF
sed -i "s|^#USUFFIX|USUFFIX|" $CONF

# enabled ldaps for TLS
CONF=/etc/default/slapd
CLIENT_CONF=/etc/ldap/ldap.conf
sed -i "s|^SLAPD_SERVICES.*|SLAPD_SERVICES=\"ldap:/// ldapi:/// ldaps:///\"|" $CONF

service slapd start

# update local client ldap.conf to point to correct CA cert location
sed -i "/^TLS_CACERT/ s|/etc.*|/etc/ldap/tls/ca_cert.pem|" $CLIENT_CONF

# point Webmin LDAP-client module to correct conf
sed -i "/^auth_ldap/ s|=.*|=$CLIENT_CONF|" /etc/webmin/ldap-client/config

# generate TLS certs and re-initialize ldap
turnkey-regen-ldap-certs $LDAP_DOMAIN
/usr/lib/inithooks/bin/openldap.py --domain=$LDAP_DOMAIN --pass=$LDAP_PASS

service slapd stop

# remove samba pkg (only required for samba schema)
apt purge -y samba

# remove backup from re-initialization
rm -rf /var/backups/slapd-
rm -rf /var/backups/*.ldapdb
