#!/bin/sh -ex

LDAP_PASS=turnkey
LDAP_DOMAIN=example.com

SRC=/usr/local/src
WEBROOT=/var/www/phpldapadmin

# phpldapadmin: unpack
tar -zxf $SRC/master.tar.gz -C $(dirname $WEBROOT)
rm $SRC/master.tar.gz
mv $(dirname $WEBROOT)/phpLDAPadmin-* $WEBROOT

# copy custom templates into phpldapadmin directory
#  since overlay is applied before phpldapadmin gets unpacked the templates
#  are placed in a different directory and moved into place here
mv $(dirname $WEBROOT)/pla-templates/creation/* $WEBROOT/templates/creation
rm -r $(dirname $WEBROOT)/pla-templates

# phpldapadmin: create base configuration
cat >$WEBROOT/config/config.php<<EOF
<?php
// phpLDAPadmin configuration

\$config->custom->appearance['hide_template_warning'] = true;
// Uncomment the line below to only use the tkl custom templates
//\$config->custom->appearance['custom_templates_only'] = true;

\$servers = new Datastore();
\$servers->newServer('ldap_pla');
\$servers->setValue('server','name','TurnKey OpenLDAP');
\$servers->setValue('server','base',array('cn=config',''));
\$servers->setValue('server','hide_noaccess_base','true');
\$servers->setValue('login','bind_id','');
\$servers->setValue('custom','pages_prefix','tkl-');
\$servers->setValue('auto_number','enable',true);
\$servers->setValue('auto_number','mechanism','search');
\$servers->setValue('auto_number','search_base','');
\$servers->setValue('auto_number','min',array('uidNumber'=>2000,'gidNumber'=>2000));
?>
EOF

# phpldapadmin: tweak footer
CONF=$WEBROOT/lib/page.php
sed -i "s|</body>.*|<div id=\"turnkey-credit\" style=\"text-align:center;font-size:11px;\"><a href=\"https://www.turnkeylinux.org/openldap\">OpenLDAP Appliance</a> - Powered by <a href=\"https://www.turnkeylinux.org\">TurnKey Linux</a></div></body>';|" $CONF

# phpldapadmin: enable in lighttpd
lighty-disable-mod ssl
lighty-enable-mod phpldapadmin

# copy the samba schema to the ldap config directory
zcat /usr/share/doc/samba/examples/LDAP/samba.schema.gz > /etc/ldap/schema/samba.schema
zcat /usr/share/doc/samba/examples/LDAP/samba.ldif.gz > /etc/ldap/schema/samba.ldif

# ldapscripts: enable params to be configured in inithook
CONF=/etc/ldapscripts/ldapscripts.conf
sed -i "s|^#SERVER|SERVER|" $CONF
sed -i "s|^#BINDDN|BINDDN|" $CONF
sed -i "s|^#SUFFIX|SUFFIX|" $CONF
sed -i "s|^#GSUFFIX|GSUFFIX|" $CONF
sed -i "s|^#USUFFIX|USUFFIX|" $CONF

# enabled ldaps for TLS
CONF=/etc/default/slapd
sed -i "s|^SLAPD_SERVICES.*|SLAPD_SERVICES=\"ldap:/// ldapi:/// ldaps:///\"|" $CONF

service mysql start
service slapd start

# generate TLS certs and re-initialize ldap
/usr/lib/inithooks/firstboot.d/20regen-openldap-secrets
/usr/lib/inithooks/bin/openldap.py --domain=$LDAP_DOMAIN --pass=$LDAP_PASS

service mysql stop
service slapd stop

# remove backup from re-initialization
rm -rf /var/backups/slapd-
rm -rf /var/backups/*.ldapdb
