#!/bin/bash -e
# regenerate phpldapadmin secrets

. /etc/default/inithooks

CONF=/etc/phpldapadmin/config.php
SECRET=$(mcookie)$(mcookie)

sed -i "\|config->custom->session.*blowfish|s|=.*|= '$SECRET';|" $CONF
